module HouseholdsHelper

  def field_title(name)
    #title = name.gsub('_', ' ')
    title = field_name_hash[name]
    return(title)
  end

  def field_name_hash
    hash = {
      'area' => 'Area of Study',
      'rnd' => 'Round',
      'city' => 'City',
      'inc_all_q5' => 'Income quintile',
      'q1_4b' => 'Gender of household head',
      'yrs_in_homec' => 'Length of residency (in years)',
      'edu_bw' => 'Highest level of education for breadwinner?',
      'under_5' => 'Number of children under the age of 5',
      'over_18' => 'Number of adults (people over 18)',
      'all_ages' => 'Number of people in the household',
      'yrs_in_home' => 'Years living in the household?',
      'q1_19' => 'Origin of household?',
      'q2_1' => 'Main source of drinking water',
      'q2_2' => 'Minutes to water source',
      'q2_3' => 'Minutes spent queuing for water',
      'q2_2s' => 'Does distance to water meet Sphere standards?',
      'q2_3s' => 'Does time spent queuing for water meet Sphere standards?',
      'q2_4' => 'Does household pay for water?',
      'ltrsppn' => 'Litres of water per person in household?',
      'ltrsppc' => 'Does litres of water per person meet Sphere standards?',
      'q2_7' => 'Household perception of water quality',
      'q3_1' => 'Toilet facility used during the day?',
      'q3_2' => 'Toilet facility used at night?',
      'q3_6' => 'Does household pay for toilet use?',
      'q3_9a' => 'Does respondent wash hands after visiting the toilet?',
      'q3_9b' => 'Does respondent wash hands before eating?',
      'q3_9c' => 'Does respondent wash hands before preparing food?',
      'q3_9d' => "Does respondent wash hands after handling child's waste?",
      'q3_9e' => 'Does respondent wash hands before feeding a child?',
      'q3_9f' => 'Does respondent wash hands after eating?',
      'q3_10' => 'How does household dispose of garbage?',
      'q4_1' => 'Main source of food?',
      'q4_2' => 'How many meals did the respondent have yesterday?',
      'q4_3' => 'Did the respondent consume a meal prepared outside the home yesterday?',
      'q4_5' => 'Did the respondent consume street food yesterday?',
      'q4_6' => 'How many meals did children in the household consume yesterday?',
      'q4_7' => 'Did children eat a meal prepared outside the home yesterday?',
      'q4_9' => 'Did children eat street food yesterday?',
      'dds' => 'Number of food groups consumed by the household yesterday (DDS)?',
      'hfias_cat' => 'Household Food Insecurity Access Scale (HFIAS)',
      'hhs_cat' => 'Houshold Hunger Scale (HHS)',
      'q4_19' => 'Did household get relief food?',
      'q4_20' => 'Did household enroll in social safety net?',
      'q4_21' => 'Did any child in the household benefit from a feeding program?',
      'fe_4wk' => 'Money (KSH) spent on food in last 4 weeks',
      'fe_inc_no' => 'Percent of household income spent on food in 4 weeks',
      'q5_1' => 'Has any member of the household been sick?',
      'q5_2' => 'How many people in the household were sick?',
      'morb_u5' => 'Percent morbidity of children under 5',
      'morb_all' => 'Percent morbidity of entire household',
      'q6_1' => 'Disputes within the household',
      'q6_3' => 'Disputes with neighbors',
      'q6_5' => 'Did household share food with neighbors?',
      'q6_6' => 'Did neighbors share food with household?',
      'q7_1a' => 'Did fire occur in the household in the last 4 weeks?',
      'q7_1b' => 'Did flooding occur in the household in the last 4 weeks? ',
      'q7_1c' => 'Did mugging or stabbing happen in the household in the last 4 weeks?',
      'q7_1d' => 'Did burglary happen in the household in the last 4 weeks?',
      'q7_1e' => 'Was the household evicted in the last 4 weeks?',
      'q7_1f' => 'Was household property destroyed in the last 4 weeks?',
      'q7_1_allc' => 'Did the household experience any of the shocks mentioned above?',
      'q7_1_all' => 'If so, how many shocks did the household experience?',
      'q7_3' => 'Feel scared walking in the community?',
      'q7_4' => 'Feel scared being in the home?',
      'q7_5' => 'Does household use avoidance measures due to insecurity?',
      'q7_6' => 'Perception of security situation in the community',
      'q8_1' => 'Type of home ownership',
      'q9_1' => 'Main source of livelihood',
      'q9_2' => 'Number of people that earn an income in the household',
      'q9_3_bw' => 'Age of breadwinner?',
      'q9_4_bw' => 'Gender of breadwinner?',
      'q9_7_bw' => 'Mode of payment for breadwinner?',
      'q9_9_bw' => 'How many hours per day does the breadwinner work?',
      'q9_10_bw' => 'How many days per week does the breadwinner work?',
      'q9_11_bw' => 'Highest level of education for breadwinner?',
      'inc_bw_no' => 'Breadwinner income in KSH (4-week recall)',
      'inc_all_no' => 'Household income in KSH (4-week recall)',
      'inc_all_q5' => 'Household Income Quintile',
      'bw_all' => 'Percent household income earned by the breadwinner',
      'nfe_4wk' => 'Money (KSH) spent on non-food items in last 4 weeks',
      'nfe_inc_no' => 'Percent of household income spent on non-food items in 4 weeks',
      'q10_1' => 'Purchased food and other items on credit?',
      'q10_1a' => 'Taken a loan to purchase food and other items?',
      'q10_2' => 'Removed children from school due to a lack of school related costs?',
      'q10_3' => 'Member of household left/moved due to lack of resources?',
      'q10_4' => 'Has any household member gone out begging for money for food?',
      'q10_5' => 'Has any household member traded sex for money or food?',
      'q10_8' => 'Has any household member stolen food or money?',
      'q10_10' => 'Has any household member received food or money from friend/neighbor/relative?',
      'q10_allc' => 'Has the household used any of the coping strategies above?',
      'q10_all' => 'If so, what proportion (out of 7 or 8, dependent on if household had children) were used?',
    }
    return(hash)
  end

end
